### ISSUE TITLE
Suggestions on the name and looks of the colorscheme

### ISSUE THREAD

**Issue by Mangeshrex** [Mangeshrex/everblush.vim#14]
Been thinking on the name of the color scheme for now and wanted to ask the users/peeps about whether the color scheme suites the color scheme or not. + Color suggestions and other port related talks are accepted. Anyone using this color scheme or just came here to have a look over repository can express their thoughts here in this Issue.

**Comment by FrenzyExists** [comment]
uwu is fine, perfect for the memes. Just add a light variant and the meme is complete

**Comment by Mangeshrex** [comment]
o.O ahh you calling my colorscheme a meme? 😂

**Comment by FrenzyExists** [comment]
Nah haha! Just the overall name `UWU` that references the meme

**Comment by Mangeshrex** [comment]
Yeah so only I wanna change the name of the theme. I want a name which suits to the colorscheme, and a name bit different. I'm looking for such names tried some but they sound meh.

**Comment by FrenzyExists** [comment]
Uwu is fine. Just needs a light variant and maybe a low or higher contrast option (ie lighter or darker version of the dark variant).

**Comment by Mangeshrex** [comment]
I've finalised the name glossy-vim/glossy.vim.

**Comment by FrenzyExists** [comment]
I'm a dark user as well. Tho, there's people out there who prefer light themes. From what I tried on my own theme, the "light" version doesn't have to be literal `#fffff`. but rather a soft gray, that could lean to the hue that the dark variant is going, like gruvbox light going for a light brown. For my own theme, its something around the gray part, but with a very minuscule blue hue (like, just a drop). You could use siduck's hex tools to brighten the background till its something around the terms of "light theme".

**Comment by Mangeshrex** [comment]
Ikr? I agree you with about the light variant I would wait till my users demand a light variant after that ofc I'm ready with the color tools and my editor. And yeah I know that #ffffff is not the only white 😂🤣. For now I can't make stuff so consistently cuz 1st- I don't have linux, 2nd - fuck clg's.

**Comment by FrenzyExists** [comment]
bruh!

**Comment by Mangeshrex** [comment]
Hey Everybody. recently I was thinking of a good name for the color scheme and came with up with the name "OVEE". If y'all have better suggestions or will to support the current one feel free to interact. 

Thank you

**Comment by ajyoon** [comment]
In my opinion, it's better to keep the current name. Even if it's not ideal (though I like the name!), the cat is already out of the bag with it being used elsewhere like in [uwu.el](https://github.com/kborling/uwu-theme.el)

**Comment by FrenzyExists** [comment]
^
This.

**Comment by FrenzyExists** [comment]
The rename is not ideal. It will cause lots of confusion, as ajyoon said, the cat is out of the box. Your _best_ option would be to risk on doing the rename, but also create another theme under the family of themes, where `uwu` is simply part of the family of themes you do, in this case representing a dark theme. It would allow you do distinct a more lighter theme under another name, or a theme with more washed colors, making the rename you want as a last name of sorts. Example:

<family-name> UwU: dark theme
<family-name> POW!: dark theme with very washed colors and less dark background

Hopefully that won't cause that much confusion. That is again, if you _really_ want to do a theme rename

**Comment by TKperson** [comment]
I really like the current name for this theme too. My reasons:
1. it stands out as a name and at least for me it's very easy to remember
2. if there's ever a light variant of this theme, its definitely going to be called "OwO"
